### ISSUE TITLE
The process to create lighting from reference image

### ISSUE THREAD

**Issue by XezXey** [andrewhou1/Shadow-Mask-Face-Relighting#10]
Hi, thanks for the great work. I would like to ask you a few questions about the lighting transfer. 
1. How can I transfer the light from the source to the reference image? 
2. Do I need other methods to perform the lighting direction estimation? I tried the EstimationLightDir.m and it outputs 8 envir_map.csv files, I don't know the meaning of those 8 files and the next step. Could you show and explain to me the step to doing this?

Thanks

**Comment by andrewhou1** [comment]
Hi there, thanks for your interest in our work!

Our method can estimate the lighting from one image (reference image) and transfer it to another (source image). First, feed the reference image to estimate its lighting. In this line "predicted_ratio = self.sess.run([self.predicted_ratio], feed_dict=ffeed_dict)", you can add self.predicted_source_lighting to the sess.run call and save out the estimated SH lighting to a text file. You would feed the reference image to the model in this case and some 9D SH vector as the target light (doesn't really matter in this first call since you're just saving out the lighting of the reference image). Then, run our model again feeding the source image and the saved estimated lighting as the target light. Let me know if any of this is unclear.

**Comment by XezXey** [comment]
Thank you for your response. I got an idea of this. thank you very much. 
So what's the use of EstimationLightDir.m and envir_map.csv?

**Comment by andrewhou1** [comment]
Oh that code is how to convert a lighting direction into SH and vice versa.
