### ISSUE TITLE
Can it run 1024 resolution images?

### ISSUE THREAD

**Issue by a656418zz** [andrewhou1/Shadow-Mask-Face-Relighting#5]
Thank you for letting me come across code that works so well, my goal is to run 1024 resolution images, how do I do that? Very much looking forward to your reply!

**Comment by andrewhou1** [comment]
The model is intended to be run on 256x256 images, however one thing you can do is resize the image from 1024x1024 to 256x256 and run it through the model. Then you can either keep the result at 256x256 or resize the result back to 1024x1024. If you do the latter, the final resized image might look somewhat blurry since the model is meant to run on 256x256.
