### ISSUE TITLE
How do you generate lighting files?

### ISSUE THREAD

**Issue by jimmysue** [andrewhou1/Shadow-Mask-Face-Relighting#7]

**Comment by andrewhou1** [comment]
Hi there and thanks for your interest in our work! By lighting files do you mean our Spherical Harmonics (SH) training and testing lightings?

**Comment by jimmysue** [comment]
> Hi there and thanks for your interest in our work! By lighting files do you mean our Spherical Harmonics (SH) training and testing lightings?

How to generate lighting file given the direction like the files in sample_lightings folder ?

**Comment by lovelylightningbug** [comment]
I just uploaded the lighting code: EstimateLightingDir.m and harmonicY.m, please check. The basic idea is we use the lighting direction to generate an environment map, and then map the environment map to SH basis function. Be careful about the projection, we need an M matrix here since it is integral over the unit sphere surface.

**Comment by 23pointsNorth** [comment]
Running `EstimateLightingDir.m` results in an error of missing `Multi-PIE_coefficients.csv`. 
Maybe I am missing something, but otherwise setting `th` and `phi` would generate the 9 coefficient.csv file similar to the ones in `sample_lightning`?
